version: 2
registries:
  rubygems-server-gems-rapidrailsthemes-com-gems:
    type: rubygems-server
    url: https://gems.rapidrailsthemes.com/gems
    username: "${{secrets.RUBYGEMS_SERVER_GEMS_RAPIDRAILSTHEMES_COM_GEMS_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_GEMS_RAPIDRAILSTHEMES_COM_GEMS_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - michellefoy
  assignees:
  - michellefoy
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.9.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: codecov
    versions:
    - 0.5.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
  - dependency-name: rubocop-rspec
    versions:
    - 1.44.1
  registries:
  - rubygems-server-gems-rapidrailsthemes-com-gems
